wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
act_noise_std:
  desc: null
  value: 0.1
actor_train_interval_step:
  desc: null
  value: 2
algorithm_name:
  desc: null
  value: qmix_ep
alpha:
  desc: null
  value: 1.0
attn:
  desc: null
  value: false
attn_N:
  desc: null
  value: 1
attn_heads:
  desc: null
  value: 4
attn_size:
  desc: null
  value: 64
automatic_entropy_tune:
  desc: null
  value: true
batch_size:
  desc: null
  value: 32
buffer_size:
  desc: null
  value: 5000
burn_in_time:
  desc: null
  value: 0
cuda:
  desc: null
  value: true
cuda_deterministic:
  desc: null
  value: true
data_chunk_length:
  desc: null
  value: 80
dropout:
  desc: null
  value: 0.0
dry_run:
  desc: null
  value: false
env_name:
  desc: null
  value: MPE
epi_dir:
  desc: null
  value: ../models/epistemic_planner/
episode_length:
  desc: null
  value: 25
epistemic:
  desc: null
  value: true
epsilon_anneal_time:
  desc: null
  value: 50000
epsilon_finish:
  desc: null
  value: 0.05
epsilon_start:
  desc: null
  value: 1.0
eval_interval:
  desc: null
  value: 10000
experiment_name:
  desc: null
  value: fix_fov03
fov:
  desc: null
  value: 0.3
gain:
  desc: null
  value: 0.01
gamma:
  desc: null
  value: 0.99
hard_update_interval:
  desc: null
  value: 200
hard_update_interval_episode:
  desc: null
  value: 100
hidden_size:
  desc: null
  value: 64
huber_delta:
  desc: null
  value: 10.0
hypernet_hidden_dim:
  desc: null
  value: 64
hypernet_layers:
  desc: null
  value: 2
layer_N:
  desc: null
  value: 1
log_interval:
  desc: null
  value: 1000
lr:
  desc: null
  value: 0.0007
max_grad_norm:
  desc: null
  value: 10.0
mixer_hidden_dim:
  desc: null
  value: 32
model_dir:
  desc: null
  value: null
n_eval_rollout_threads:
  desc: null
  value: 1
n_rollout_threads:
  desc: null
  value: 1
n_training_threads:
  desc: null
  value: 1
num_agents:
  desc: null
  value: 3
num_env_steps:
  desc: null
  value: 10000000
num_eval_episodes:
  desc: null
  value: 32
num_landmarks:
  desc: null
  value: 3
num_random_episodes:
  desc: null
  value: 5
opti_eps:
  desc: null
  value: 1.0e-05
per_alpha:
  desc: null
  value: 0.6
per_beta_start:
  desc: null
  value: 0.4
per_eps:
  desc: null
  value: 1.0e-06
per_nu:
  desc: null
  value: 0.9
play:
  desc: null
  value: false
popart_update_interval_step:
  desc: null
  value: 2
prev_act_inp:
  desc: null
  value: false
recurrent_N:
  desc: null
  value: 1
save_interval:
  desc: null
  value: 100000
scenario_name:
  desc: null
  value: simple_spread
seed:
  desc: null
  value: 1
share_policy:
  desc: null
  value: true
stacked_frames:
  desc: null
  value: 1
target_action_noise_std:
  desc: null
  value: 0.2
target_entropy_coef:
  desc: null
  value: 0.5
tau:
  desc: null
  value: 0.005
train_interval:
  desc: null
  value: 100
train_interval_episode:
  desc: null
  value: 1
use_ReLU:
  desc: null
  value: true
use_average_pool:
  desc: null
  value: true
use_cat_self:
  desc: null
  value: true
use_centralized_Q:
  desc: null
  value: true
use_conv1d:
  desc: null
  value: false
use_double_q:
  desc: null
  value: true
use_eval:
  desc: null
  value: true
use_feature_normalization:
  desc: null
  value: true
use_huber_loss:
  desc: null
  value: false
use_max_grad_norm:
  desc: null
  value: true
use_naive_recurrent_policy:
  desc: null
  value: true
use_obs_instead_of_state:
  desc: null
  value: false
use_orthogonal:
  desc: null
  value: true
use_per:
  desc: null
  value: false
use_popart:
  desc: null
  value: false
use_reward_normalization:
  desc: null
  value: true
use_rnn_layer:
  desc: null
  value: true
use_same_share_obs:
  desc: null
  value: true
use_soft_update:
  desc: null
  value: true
use_value_active_masks:
  desc: null
  value: false
use_wandb:
  desc: null
  value: true
user_name:
  desc: null
  value: elles
weight_decay:
  desc: null
  value: 0
